name: 自动化
on:
  push:
    branches:
      - master

jobs:
  build:
    name: 测试+构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 搭建 Node 环境
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-elon-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-elon-

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: 测试
        run: npm run test:ci

      - name: 测试失败推送
        if: ${{ failure() }}
        uses: ghostoy/dingtalk-action@master
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          secret: ${{ secrets.DINGTALK_SECRET }}
          msgtype: 'actionCard'
          content: |
            {
              "title": "测试失败",
              "text": "测试失败",
              "btnOrientation": "0",
              "btns": [{
                "title": "查看项目",
                "actionURL": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
            }

      - name: 构建
        run: npm run build

      - name: 上传打包文件
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    name: 部署
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@master
      - name: 下载打包文件
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Firebase 部署
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  notice:
    name: 通知
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 发布成功的推送
        if: github.ref == 'refs/heads/master'
        uses: ghostoy/dingtalk-action@master
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          secret: ${{ secrets.DINGTALK_SECRET }}
          msgtype: 'actionCard'
          content: |
            {
              "title": "部署成功", 
              "text": "![img](https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60) \n\n仓库: [${{ github.repository }}](https://github.com/${{ github.repository }}) \n\n操作: ${{ github.actor }} 更新正式服 ",
              "btnOrientation": "0", 
              "btns": [{
                "title": "查看项目", 
                "actionURL": "https://elonwu.site"
              }]
            }
